### ISSUE TITLE
Liste porteurs de parts

### ISSUE THREAD

**Issue by friantcedric** [pobsteta/michaut#5]
Ci joint la liste des porteurs de parts pour import dans l'appli
[Liste porteurs de Parts.xlsx](https://github.com/pobsteta/michaut/files/1332982/Liste.porteurs.de.Parts.xlsx)

 . Un Groupement Forestier par Onglet.

**Comment by pobsteta** [comment]
Les colonnes sont manquantes dans les onglets pour permettre l'import des actes (manque parfois dateacte, rang, code_adherent_us) !
